### PR TITLE
Chris/sort ints

### PR DESCRIPTION
**Pull request by chris-malloy**

### CODE REVIEW

**Comment by ahmedlearns** [comment]
Is it normal to have a bunch of submodules as such in Go? Not very familiar with it

**Comment by chris-malloy** [comment]
> Is it normal to have a bunch of submodules as such in Go? Not very familiar with it

@jduv can speak to it a little more, but dep management in Go is unfortunately kind of a pain. I modeled this after our lambda deployments, and deps in that world simply have to be resolved within the local scope of the project. Golang wants to resolve deps globally on your machine (I can't stand this about go). I will try another example in Go where I attempt to resolve the deps globally, and that should allow for a cleaner module structure.

**Comment by AlexMcConnell** [comment]
Wow, look at the size of that function! Look at all those conditionals! Uncle Bob says try this:

```
func sortInts(arr []int) ([]int, error) {
  switch len(arr) {
  case 0:
    return make([]int, 0), nil
  case 1:
    return arr, nil
  default:
    return allTheRestOfThatCodeInSomePrivateMethod(arr)
  }
}
```

For the rest of it, try using a struct and recursion

**Comment by chris-malloy** [comment]
> Wow, look at the size of that function! Look at all those conditionals! Uncle Bob says try this:
> 
> ```
> func sortInts(arr []int) ([]int, error) {
>   switch len(arr) {
>   case 0:
>     return make([]int, 0), nil
>   case 1:
>     return arr, nil
>   default:
>     return allTheRestOfThatCodeInSomePrivateMethod(arr)
>   }
> }
> ```
> 
> For the rest of it, try using a struct and recursion

yay mob programming. thank you for fixing it for me.

**Pull request merged**
